services:
  stitchcore:
    image: stitchcore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4308:4308
    volumes:
      - stitchcore_cache:/data
      - /tmp:/tmp
    user: "1001:1001"

volumes:
  stitchcore_cache:
    driver: local
