services:
  stitchcore:
    image: stitchcore
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "0:0"
    ports:
      - 4308:4308
    volumes:
      - stitchcore_cache:/data
    restart: unless-stopped

volumes:
  stitchcore_cache:
    driver: local
