services:
  stitchcore:
    image: stitchcore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4308:4308
    volumes:
      - stitchcore_cache:/data

volumes:
  stitchcore_cache:
    driver: local
